# Generated by Django 3.1.4 on 2020-12-12 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20201211_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='dexcription',
            new_name='description',
        ),
    ]
