# Generated by Django 3.1.4 on 2020-12-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20201212_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
